apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o charts/idc-stack -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o charts/idc-stack -f docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: API_DB_HOST
              value: bolt://neo4j-db:7687
            - name: API_DB_PASSWORD
              value: letmein
            - name: API_DB_USER
              value: neo4j
            - name: API_PORT
              value: "4000"
          image: maxandersson/icd-api
          name: api
          ports:
            - containerPort: 4000
          resources: {}
      restartPolicy: Always
status: {}
