apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o charts/icd-stack -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: neo4j-db
  name: neo4j-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neo4j-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o charts/icd-stack -f docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: neo4j-db
    spec:
      containers:
        - env:
            - name: NEO4J_AUTH
              value: neo4j/letmein
            - name: NEO4J_dbms_security_procedures_unrestricted
              value: apoc.*
          image: {{.Values.db.image}}
          name: neo4j-db
          ports:
            - containerPort: 7474
            - containerPort: 7687
          resources: {}
      restartPolicy: Always
status: {}
